### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by Cuperino** [mahdize/CrossQFile#1]
Hello @mahdize,

This is awesome! Could you make this project open source with a license approved by either the Open Source Initiative or the Free Software Foundation? I would like to make use of this in [QPrompt Teleprompter App](https://github.com/Cuperino/QPrompt), but all the libraries I incorporate must be open source and compatible with the project's license, the GPLv3.

Any license you choose is fine by me, even if I can't use it. The problem is that if you don't specify a license, your code is still fully protected by your copyright in many parts of the world, and no one should use it without your explicit permission.

**Comment by Cuperino** [comment]
Soft copyleft licenses, such as the BSD 3-clause license, the LGPL, and the MIT license are recommended to encourage developer adoption.

**Comment by mahdize** [comment]
Hi @Cuperino,

A MIT License has been added to the project. thank you for the contribution.

**Comment by Cuperino** [comment]
Thank you for creating it!
